### ISSUE TITLE
WebRTC transport for runtime protocol

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#134]
WebRTC does nice things like NAT traversal, and peer-to-peer communication between browser clients. Using it for the runtime protocol should enable:
* connecting to a running client-side NoFlo runtime, for debugging/monitoring
* connecting Flowhub "in the cloud" to a device/runtime which is not directly on the Internet

**Comment by bergie** [comment]
This is now in.

**Comment by jonnor** [comment]
https://github.com/noflo/noflo-runtime-webrtc
