### ISSUE TITLE
Generate correlation ID for a network's execution.

### ISSUE THREAD

**Issue by hayesmg** [noflo/noflo#162]
It would be nice to have a unique ID represent the execution of a network from start to finish.  An example purpose for this ID would be to correlate log entries.

**Comment by bergie** [comment]
This will be provided via the `scope` feature in #356

**Comment by bergie** [comment]
Scopes are in released NoFlo, so for correlation IDs one just needs to send the initial packets (from outside, from a generator) with a `scope` set.
