### ISSUE TITLE
Return non-transpiled code (CoffeeScript) on component:getSource

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#171]
To be able to show sane component code in noflo-ui (noflo/noflo-ui#223) for component implemented in CoffeScript.
This could be done by looking up the code in Github based on the component library metadata (repo url, version).

**Comment by bergie** [comment]
The new manifest format in https://github.com/flowbased/fbp-manifest allows providing a separate source path from "executable path". We could make the browser builds point these to a URL.

**Comment by jonnor** [comment]
Sourcemaps are also interesting, as they allow exception etc to also refer to the correct place in the code.

**Comment by bergie** [comment]
Moved to noflo/grunt-noflo-browser#19
