### ISSUE TITLE
FBP protocol for values on port should allow human readable names

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#173]
Currently "values" on "inport" of component:component message just takes an array of values. I think it instead should take an array of { "id": "my-id",  "name": "MyHumanId" }.
The "id" would be what is stored as an IIP, and "name" what is shown in UI. id could potentially be an integer value.
This is also more extensible in case there are other things we have not thought about.

**Comment by bergie** [comment]
Moved to flowbased/fbp-protocol#8
