### ISSUE TITLE
NoFlo for the Browser -- Builder broken

### ISSUE THREAD

**Issue by jezaman** [noflo/noflo#175]
The builder on http://noflojs.org/download/ is broken.
Trying to create the JS file leads to an Application Error on herokuapp

**Comment by bergie** [comment]
Keeping this issue open as it relates to switching from component.io to NPM+WebPack

**Comment by bergie** [comment]
As of grunt-noflo-browser 1.0.0-alpha4 we can now build noflo, typical module packages, and noflo-ui with webpack. Closing this issue.
