### ISSUE TITLE
Allow graph description

### ISSUE THREAD

**Issue by cwohlman** [noflo/noflo#196]
If we can use graphs as components we should be able to specify an icon and description for when the graph is displayed in the component library of noflo-ui or anywhere else component description is used.

I've been digging around in the code to try and implement this but can't find the right hooks to add this functionality. If anyone could give me some pointers I'd be glad to implement this myself and send a pull request.

**Comment by bergie** [comment]
Moved to flowbased/fbp-protocol#10
