### ISSUE TITLE
Addressable port in WirePattern behaves incorrectly when receiving IP from another component

### ISSUE THREAD

**Issue by paulyoung** [noflo/noflo#252]
The issue I'm seeing as that a packet sent from a component isn't being converted into an object with array indexes as keys.

I have a component which sends a string from its `NAME` out port to an `addressable` port on another component like so:

``` fbp
Create(CreateTask) NAME -> TASKS[0] List(ListTasks)
```

Here, `data.tasks` is `My task` in the WirePattern `proc` function.

However, passing a string identical to the one sent above produces the expected result:

``` fbp
'My task' -> TASKS[0] List(ListTasks)
```

`data.tasks` is `{ '0': 'My task' }`

My tests for this component pass but they only send IIPs. I only saw the issue when sending an IP from another component when running a graph.

**Comment by bergie** [comment]
Fixed via the Process API port of WirePattern #526
