### ISSUE TITLE
noflo.loadFile - How to know that all IIPs have been sent?

### ISSUE THREAD

**Issue by sjaakiejj** [noflo/noflo#261]
I'm currently trying to test some of my noflo graphs, but ran into an issue regarding IIPs. Some of my components take some extra parameters as IIPs, so I specify those as data packets in the JSON graph file. But noflo.loadFile returns before these packets are sent to the components. This is the order of execution that I generated by putting print statements into the noflo methods:

[TEST] Loading graph file
[NETWORK] Starting Network...
[NETWORK] Network.prototype.sendInitials called
[NETWORK] Network.prototype.sendInitials.send called
[NETWORK] Network Started
...
[NETWORK] Network.prototype.sendInitials processing initials
[NETWORK] Network.prototype.addInitial called
[NETWORK] Expecting 1 initializations
[NETWORK] Network.prototype.addInitial called
[NETWORK] Expecting 2 initializations
[TEST] Graph file returned. 2 initializations pending
...
[NETWORK] Network.prototype.sendInitials processing initials
[NETWORK] Network.prototype.sendInitials processing initials
[NETWORK] Expecting 1 initializations
[NETWORK] Expecting 0 initializations

So my question is - how do I know that all the IIPs have been sent to their associated components to ensure the system has completely started?

Right now I'm using a timeout function, but that's not exactly robust.

**Comment by jonnor** [comment]
Ran into the same issue in `noflo-runtime-msgflo` now, trying to set/override some 'IIPs' after a NoFlo component has been started.
Due to the way Network.sendInitials() do work async, there is no way to know when all IIPs have been sent...
