### ISSUE TITLE
ComponentLoader is not concurrent

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#263]
When `ComponentLoader` is started on several concurrent requests, only the first attempt to load the component library succeeds and all the consequent attempts fail. This happens because `read-installed` is not thread-safe and returns empty list for the consequent pending requests.

Updating `read-installed` to 3.x might fix this.

**Comment by bergie** [comment]
Probably less of an issue when using `--cache`? But anyway, looks like `read-installed` is now at 4.0

**Comment by jonnor** [comment]
Needs re-testing.

**Comment by bergie** [comment]
We're now using fbp-manifest which does read packages concurrently
