### ISSUE TITLE
WirePattern: Copy params and provide as function argument?

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#266]
Problematic case:
- Send data on param inport
- Send data on regular inport. This registers an async callback which depends on a param
- Send new data on param inport
- Async task completes, does some work which depends on a param

The async task will now have different parms used for registration and used in the callback.

**Comment by bergie** [comment]
We have [Process API](http://bergie.iki.fi/blog/noflo-process-api/) now, and hence it doesn't really make sense to add features to WirePattern.
