### ISSUE TITLE
graph.loadJSON synchronous but needs callback

### ISSUE THREAD

**Issue by forresto** [noflo/noflo#268]
To load a noflo graph from JSON we have to do something like:
```
jsonGraph = require './fixtures/graph.json'
nfGraph = null
Noflo.graph.loadJSON jsonGraph, (graph) -> nfGraph = graph
```

`loadJSON` isn't an asynchronous operation, so we shouldn't need a callback. 

We could add `return graph` after [this line](https://github.com/noflo/noflo/blob/21f9aa1674d35f1ed0fbfa80450914a418ffe7b2/src/lib/Graph.coffee#L831). Then this would work:
```
jsonGraph = require './fixtures/graph.json'
nfGraph = Noflo.graph.loadJSON jsonGraph
```

The callback method would still work. Any reason to not do this?

**Comment by jonnor** [comment]
Don't think we're gonna do something about this. Closing
