### ISSUE TITLE
WirePattern duplicate groups on output

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#269]
More details here: http://stackoverflow.com/questions/28201084/forward-only-a-single-group-using-the-wirepattern-helper-when-config-group-is-tr

Seems to affect sync components only.

**Comment by bergie** [comment]
We're also seeing duplicated groups on `error` callback of async components: https://travis-ci.org/noflo/noflo-rss/builds/134564008#L266

cc/ @jonnor

**Comment by bergie** [comment]
This no longer happens with the Process API implementation from #526
