### ISSUE TITLE
Reduce time taken for each call to outport.send() in the browser

### ISSUE THREAD

**Issue by robhawkes** [noflo/noflo#270]
From my own testing it looks like `outport.send()` takes between 0.5–0.7ms to return, assuming a best-case scenario of the packet being completely empty and the out-port going to a `core/Drop` process. This seems far too long if you want to be able to do things like processing lots of individual items in a graph (eg. breaking down a large array and sending each component out as a packet). For example, I have an array of 144 items and overall it takes around 70ms(!) to finish sending all the packets using `objects/SplitArray`. And that's a small array…

Surely there's a way to reduce the amount of time `outport.send()` takes in a best-case scenario (assuming a blank packet). In comparison, the same graph on Node.js takes around 0.11ms to return each call to `outport.send()`, which arguably is still quite a long time when you consider sending packets for each item in arrays of 1000 items of more (over 1/10th of a second just to send 1000 blank packets!).

Perhaps I'm misunderstanding the limitations of NoFlo and its event-based architecture, though these kind of delays (which will be multiplied as the packets are further passed along and processed) really take the shine of NoFlo as a viable alternative to the way things are done currently (eg. processing the same 1000 array items taking a tiny fraction of the time it takes in NoFlo).

I'm very keen to hear whether this is, a) a known issue, and b) something that will be looked at for improvement.

**Comment by alfa256** [comment]
+1
A small benchmark should be in order to make improvements.

**Comment by robhawkes** [comment]
I don't know how that benchmark should look but I'm happy to have a go if we can work out its rough structure. Right now I'm just testing it via custom components and the high-res `performance.now()` timing API.

**Comment by robhawkes** [comment]
I'd quite like to play around with the `EventEmitter` used in the browser version of NoFlo but on a quick glance I can't find where it's pulled in from. Can someone point it out and I'll see if there are any quick optimisations that could be done on the `emit` method (assuming that's where the delay is)?

**Comment by robhawkes** [comment]
I've done some benchmarking in the browser comparing [EventEmitter](https://github.com/Wolfy87/EventEmitter), [WlldEmitter](https://github.com/HenrikJoreteg/wildemitter) and [EventEmitter2](https://github.com/asyncly/EventEmitter2). I think the results speak for themselves!

```javascript
// Time in milliseconds to call .emit("test") once with a single listener each
EventEmitter: 0.17500005196779966
WildEmitter: 0.32899994403123856
EventEmitter2: 0.053999945521354675
```

```javascript
// Time in milliseconds to call .emit("test") 100 times with a single listener each
EventEmitter: 0.5680000176653266
WildEmitter: 0.6939999293535948
EventEmitter2: 0.12700003571808338
```

**Comment by jonnor** [comment]
@robhawkes Interesting. Can you run some tests with multiple listeners? 3 and 10 for instance?

**Comment by robhawkes** [comment]
// ms times for 1 .emit() call and 10 listeners
```
EventEmitter: 0.17200002912431955
WildEmitter: 0.29200001154094934
EventEmitter2: 0.07599999662488699
EventEmitter3: 0.265000038780272
bergie/emitter: 0.14700007159262896
```

// ms times for 100 .emit() calls and 10 listeners
```
EventEmitter: 1.2339999666437507
WildEmitter: 1.478999969549477
EventEmitter2: 0.6140000186860561
EventEmitter3: 0.7299999706447124
bergie/emitter: 0.775999971665442
```

// ms times for 1,000 .emit() calls and 10 listeners
```
EventEmitter: 11.360000004060566
WildEmitter: 5.018000025302172
EventEmitter2: 1.9909999100491405
EventEmitter3: 1.2839999981224537
bergie/emitter: 3.0610000248998404
```

// ms times for 100,000 .emit() calls and 10 listeners
```
EventEmitter: 422.7909999899566
WildEmitter: 318.76300007570535
EventEmitter2: 126.27300003077835
EventEmitter3: 71.41800003591925
bergie/emitter: 229.13999995216727
```

// ms times for 1,000,000 .emit() calls and 10 listeners
```
EventEmitter: 4673.170999973081
WildEmitter: 3401.6759999794886
EventEmitter2: 1148.3129999833182
EventEmitter3: 641.9809999642894
bergie/emitter: 2427.3149999789894
```

**Comment by jonnor** [comment]
With 10 the differences between current and EventEmitter3 are much smaller, but EventEmitter3 is still significantly faster.

**Comment by robhawkes** [comment]
EE3 definitely seems a lot better at scale, though EE2 is far faster for requirements like mine where there are many emit calls but few listeners. I'm trying to build NoFlo using EE2 + EE3 but I can't even get it to even build, probably because I don't understand what I need to do with the Component process!

**Comment by bergie** [comment]
@robhawkes on a quick look you should only need to add `asyncly/eventemitter2` to `component.json` to get it installed for the browser build.

**Comment by trustmaster** [comment]
Great job on benchmarks @robhawkes :+1: 

Looking through the code of those emitters, all of them are based on direct function calls and therefore are synchronous. It's 2015 now and still no native EventEmitters on browser? I wonder how something like https://developer.mozilla.org/en-US/docs/Web/API/Event.Event would behave.

**Comment by robhawkes** [comment]
I managed to get a build working but it's taking me far too long to fiddle with things and I don't know enough about what I'm doing with a custom NoFlo browser build to ensure I can do a proper test with my own components.

I'm very interested to see how someone who knows what they're doing gets on as my use-case is processing many arrays of items as realtime data comes in – speeding this up is important.

**Comment by bergie** [comment]
Since then we've moved browser builds to WebPack, and use the EventEmitter library from there

**Comment by bergie** [comment]
Closing since there has been no further information
