### ISSUE TITLE
use coffee-cache

### ISSUE THREAD

**Issue by ensonic** [noflo/noflo#272]
https://www.npmjs.com/package/coffee-cache

before:
$ xtime node_modules/.bin/noflo >/dev/null list .
1.99u 0.10s 2.00r 64896kB node_modules/.bin/noflo list .

hack it:
$ export COFFEE_CACHE_DIR=/tmp/coffee-cache
$ mkdir $COFFEE_CACHE_DIR
$ sed -i "2 i\require\(\'coffee-cache\'\)" node_modules/noflo/bin/noflo

after:
$ xtime node_modules/.bin/noflo >/dev/null list .
1.99u 0.20s 2.06r 66444kB node_modules/.bin/noflo list .
$ xtime node_modules/.bin/noflo >/dev/null list .
0.90u 0.11s 0.91r 57476kB node_modules/.bin/noflo list .

$ find $COFFEE_CACHE_DIR -name "*.js" | wc -l
146

This would help https://github.com/noflo/noflo-ui/issues/322 and apparently also is something that is done in https://github.com/noflo/noflo-gnome/blob/master/src/codeLoader.js#L75.

Mostly posting this for discussion here, as I'd love to avoid patching node_modules/.bin/noflo.

**Comment by trustmaster** [comment]
Any known side effects?

**Comment by bergie** [comment]
This sounds very interesting for environments like https://github.com/c-base/ingress-table where the start-up time is long due to slow IO and slow processor

**Comment by ensonic** [comment]
I've tested it also on a arm9 @ 300 MHz and there the improvement is 3 min -> 1 min. So far I've not seen any issues. I'll do more tests tomorrow and then make a patch as well.

**Comment by bergie** [comment]
@ensonic sounds great! I think enabling/disabling cache could be a command-line option for `noflo` and `noflo-nodejs` commands

**Comment by jonnor** [comment]
@ensonic What happens with dynamically registered components, like when editing in Flowhub? Is there risk of stale cached .js in that case?

**Comment by ensonic** [comment]
I can't test the dynamic editing right now, as this is broken in noflo-ui right now. Trying to open a component that is on a noflo-nodejs runtime, just spins forever (can't find the bug for that right now).

**Comment by bergie** [comment]
I've added `coffee-cache` support to noflo-nodejs. NoFlo 0.5.12 also has a component registry cache.

https://github.com/noflo/noflo-nodejs/commit/3c092b4c4063fa47fe5db38cfea9821c8830f339
