### ISSUE TITLE
WirePattern doesn't obey arrayPolicy "any"

### ISSUE THREAD

**Issue by robhawkes** [noflo/noflo#275]
I've hit a bit of an issue with the WirePattern helper that's causing it to not trigger the data function when receiving a packet on one of the in ports. The `arrayPolicy` for the in ports is set to `"any"` and yet the component is behaving as if `arrayPolicy` is set to `"all"` (eg. it's waiting for data on all in ports before triggering the data function).

Is this known? It's really easy to reproduce and [the NoFlo tests](https://github.com/noflo/noflo/blob/master/spec/Helpers.coffee) don't seem to check for the combination where `arrayPolicy` is set to `"any"` but data is received on only one of the in ports. In all the tests data is received on all the defined in ports so this doesn't manifest.

**Comment by trustmaster** [comment]
`arrayPolicy` only applies do different indexes of the same `addressable` port (ArrayPort in FBP terms). WirePattern currently doesn't support `any` policy for its grouped `in` ports, that behavior is provided by particular port events.

**Comment by robhawkes** [comment]
I see. While that me be so, the behaviour for `arrayPolicy.params` seems to be different, in that it allows you to wait for data on all the param ports before moving on (hence expecting this for in ports). If this isn't the intended behaviour for in ports too then I'd suggest this being separated in the WirePattern configuration as it's confusing.

Having the ability to wait for one of many in ports before moving on would be an incredibly useful feature, especially as the same behaviour is already provided for parameter ports. It would be a shame to have to create individual port handlers on top of the WirePattern data handler.

**Comment by trustmaster** [comment]
@robhawkes We're planning to merge WirePattern into `noflo.Component` given all the practical observations such as this issue. We also plan to replace the current port binding in WirePattern with the concept of Firing Patterns which would allow you to set activation masks and bind different handler functions to them. That would be better than adding even more cumbersome configuration to WirePattern.

**Comment by robhawkes** [comment]
Sounds great, I can't wait to see those improvements rolled in. I love the WirePattern but I feel I'm in an either/or situation with things like this so I'm having to end up building custom components that do similar things.

**Comment by robhawkes** [comment]
Has there been any progress with this?

**Comment by trustmaster** [comment]
@robhawkes We discussed WirePattern update during a mini NoFlo meetup in April, you can find the protocol here: https://docs.google.com/document/d/1_7ExwbugP8Q8LNaaysRwWxny9sgb9FomXL0Vs8sU0cc/edit#heading=h.ggqvo151ftpf

I started with the implementation but it is currently suspended until we roll out The Grid Beta, afterwards we plan to work on NoFlo 0.6 update.

**Comment by bergie** [comment]
Should be fixed via #526
