### ISSUE TITLE
WirePattern doesn't forward groups correctly when edges to in-port and param-port are both async

### ISSUE THREAD

**Issue by robhawkes** [noflo/noflo#276]
I've bumped into a blocking issue for my use-case in which the WirePattern fails to forward groups correctly when both its in-port and single parameter port are connected to asynchronous components.

For example, take this graph:

![](http://cl.ly/image/2k39351G3o21/Screen%20Shot%202015-02-19%20at%2015.43.13.png)

The 2 `ajax/Get` components are async and the WirePattern component waits for them before calling its data function. So far so good. The problem lies in the forwarding of the groups, as can be seen when inspecting the edge of the WirePattern out port:

![](http://cl.ly/image/183y3x3q2z0o/Screen%20Shot%202015-02-19%20at%2015.47.29.png)

You can see that the groups are forwarded, but with no data. And when the data does get sent, it has no groups!

Any idea what's going on and whether this is a known issue?

Also, I'd appreciate suggestions on how to work around this in the interim.

Here's the code for the WirePattern component in the above example:

``` javascript
var noflo = require("noflo");

(function(exports) {
  var WPBug = function() {
    var self = this;

    noflo.Component.call(self);

    self.description = "";

    var config = {
      in: ["async1"],
      params: ["async2"],
      out: "out",
      forwardGroups: true,
      arrayPolicy: {
        in: "any",
        params: "all"
      }
    };

    self.inPorts = new noflo.InPorts({
      async1: {
        datatype: "all"
      },
      async2: {
        datatype: "all",
        required: true
      }
    });

    self.outPorts = new noflo.OutPorts({
      out: {
        datatype: "all"
      }
    });

    noflo.helpers.WirePattern(self, config, function(async1, groups, outPort) {
      outPort.send(async1, self.params.async2);
    });
  };

  WPBug.prototype = Object.create( noflo.Component.prototype );

  exports.getComponent = function() {
    return new WPBug;
  };
})(typeof exports === "undefined" ? this["WPBug"] = {} : exports);
```

**Comment by robhawkes** [comment]
It's been about 4 months without reply, has anyone got a clue about this? I've stopped using NoFlo for the time-being as I need functionality like this to be able to take the plunge and implement it as a core part of the platform I'm building. Otherwise, I'll have to resort to building my own which is not something I'd like to do if possible.

**Comment by trustmaster** [comment]
@robhawkes To be clear, WirePattern doesn't forward groups arriving at Param ports. And normally group forwarding works like this:

1. Grab all groups coming to an `in` port until a `data` packet.
2. Flush all groups when `data` arrives.
3. Process `data` and send results.
4. Close as many groups as needed.

This is called data-sensitive or data-triggered behavior and it is the most common yet not the only one supported in NoFlo. For more advanced cases like handling complex nested substream structures, there are two options available:

 - Raw ports API (without WirePattern)
 - `receiveStreams` option. It is not documented but there are examples in tests: https://github.com/noflo/noflo/blob/master/spec/Helpers.coffee#L475

Unfortunately I couldn't deduce the exact packet sequence from the above screenshot (it should include group ends and disconnect packets for picture to be complete) so I can't tell for sure if it's a known issue or not. Sorry, I missed original bug report back 4 months ago too.

**Comment by bergie** [comment]
Bracket forwarding should be a lot more robust now that we're using Process API internally in WirePattern (#526)
