### ISSUE TITLE
Download for noflo browser version not working

### ISSUE THREAD

**Issue by Gytaco** [noflo/noflo#277]
The current link and options do not allow you to download the prebuilt script.

http://noflojs.org/download/

Error below

An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by bergie** [comment]
Good point. I think in general we should retire that interface and instead focus on providing NoFlo to browsers via component.io (already works well) and NPM/browserify

**Comment by Gytaco** [comment]
I haven't seen any info on the component.io option? How far is the browserify version from being stable??

**Comment by jonnor** [comment]
Browserify is experimental, will be that way until someone gives it another couple of days of dedicated time.

**Comment by bergie** [comment]
Duplicate of #175
