### ISSUE TITLE
renaming graph port to same name deletes the port

### ISSUE THREAD

**Issue by akonsu** [noflo/noflo#278]
this line https://github.com/noflo/noflo/blob/74a554774c1d97e08f6d98b950f9959980fe4f48/src/lib/Graph.coffee#L155 deletes the old port on renaming, and if the new name is the same, as the old one then the port just gets deleted. same in the `renameOutport`.

**Comment by forresto** [comment]
Doesn't the return short-circuit that situation? https://github.com/noflo/noflo/blob/74a554774c1d97e08f6d98b950f9959980fe4f48/src/lib/Graph.coffee#L151

(And hi from StackOverflow yesterday... small world :wink:)
