### ISSUE TITLE
documentation should use package.json for install

### ISSUE THREAD

**Issue by 7yl4r** [noflo/noflo#282]
I'm not sure this is the correct repository to file this under, but I can't find a repository specifically for the documentation listed on noflojs.org. 

The getting started section covers how to create a package.json file and then diverges to manually install required packages with npm. Why not use the package.json `dependencies` or `dev-dependencies` and then do one `npm install`? I'll happily make this edit if someone can point me to right place to do it.

**Comment by aretecode** [comment]
https://github.com/noflo/noflo.github.io

It is being updated here https://github.com/aretecode/noflo.github.io/tree/gh-pages
