### ISSUE TITLE
I want to know the relationship/difference among these projects

### ISSUE THREAD

**Issue by ddnionio** [noflo/noflo#283]
I plan to develop based on the noflo and confused with the following project.

flowbased/fbp-protocol-client https://github.com/flowbased/fbp-protocol-client/
noflo/noflo-runtime-base https://github.com/noflo/noflo-runtime-base/
noflo/noflo-runtime https://github.com/noflo/noflo-runtime https://github.com/noflo/noflo-runtime
noflo/noflo https://github.com/noflo/noflo/

Could you tell me the relationships among those, thanks.

**Comment by bergie** [comment]
* fbp-protocol-client: JavaScript client library for connecting to various FBP runtimes (NoFlo, MicroFlo, JavaFBP, etc)
* noflo-runtime-base: transport-agnostic library for exposing NoFlo as a FBP runtime (with transports at -websocket, -iframe, -webrtc)
* noflo-runtime: set of NoFlo components for working with FBP runtimes, used mainly by NoFlo UI
* noflo: the actual NoFlo library/runtime
