### ISSUE TITLE
IIP not present in JSON format

### ISSUE THREAD

**Issue by schmurfy** [noflo/noflo#285]
Maybe that's a misunderstanding on my side but how can the graph be fully rebuilt without it ?

**Comment by schmurfy** [comment]
I found it in the connections which, I suppose, is a design choice.
I find it a bit weird to have a disconnect between the api (set_initial) and where it ends up being stored (connections) although having it in connections make more sense to me than the set/remove_initial api.

**Comment by jonnor** [comment]
The API was specced some years after the JSON graph format.
Reason it was split out in the API I suspect is that often or nearly always there is different code paths that need to be triggered depending on if something is an IIP or a connection. A bit cleaner
with dedicated messages in that case.
Every implementation I know of checks whether something is an IIP when iterating the connections in the JSON graph format.

**Comment by schmurfy** [comment]
I also end up checking whether a connection is a real connection or a data input now but having all the inputs in one place also help in some ways, instead of having to check two or more arrays to find if your node is connected and to what.

Thanks for the explanations :)
