### ISSUE TITLE
Using NoFlo components in an AngularJS project within a php project

### ISSUE THREAD

**Issue by xtrasmal** [noflo/noflo#286]
'm wondering what steps I should take to accomplish the following:

I've got a existing php project. In the backend I've got things that I would like the user to visually connect. The data source is an API call to a json resources.

The backend is not a single page app, but I am using AngularJS to help with the interaction. I was looking for a graph library where I could connect certain blocks or some kind of svg tool.

KinectJS is not used anymore, D3js is quite nice, but both are pretty rough to go through.

Now that I came across NoFlo, I was wondering how I can add the javascript libraries to my existing code, so that I can use the node to port functionality.

Can somebody show me how I can do that?

**Comment by jonnor** [comment]
Hi, sorry for the late reply.

You can either implement the [FBP protocol](http://noflojs.org/documentation/protocol/) (typically over WebSockets) in your backend, and then [Flowhub](app.flowhub.io)/[noflo-ui](http://github.com/noflo/noflo-ui) directly against it.

Alternatively, you can use the underlying editor [TheGraph](http://github.com/the-grid/the-graph)
