### ISSUE TITLE
The noflo.js customiser for the browser crashes

### ISSUE THREAD

**Issue by th0br0** [noflo/noflo#288]
Regardless of the configuration options, the Heroku app seems to crash.

http://noflojs.org/download/

**Comment by jonnor** [comment]
Yes, it has been broken since forever. Install noflo and component libs using NPM/component.io

**Comment by jonnor** [comment]
Here is a helper grunt task: https://github.com/noflo/grunt-noflo-browser

**Comment by bergie** [comment]
Duplicate of #175
