### ISSUE TITLE
How to use a CLI as a noflo component?

### ISSUE THREAD

**Issue by rjsteinert** [noflo/noflo#289]
Hi there - I've written a ton of CLI in different languages and don't want to port them to javascript. I think noflo is rad so I'm hoping someone has already explored ways to wrap a CLI up as noflo component.  Anyone have any leads?

**Comment by bergie** [comment]
Here is an example: https://github.com/noflo/noflo-tika/blob/master/components/ToHtml.coffee

**Comment by rjsteinert** [comment]
Thanks @bergie
