### ISSUE TITLE
Grouping components

### ISSUE THREAD

**Issue by ilanbiala** [noflo/noflo#291]
Is there a way to group components under 1 large group instead of creating multiple graphs? For example, I'd like to have a state and step component, with a step having multiple states. Can I do that and have that exported in the JSON?

**Comment by ilanbiala** [comment]
If I have to use multiple graphs, how can I connect a graph to another in Flowhub?

**Comment by jonnor** [comment]
A graph becomes a new component. The exported ports of the graph becomes the externally visible ports. You can use this in another graph by referring to it by name.
