### ISSUE TITLE
Async Component Javascript Example

### ISSUE THREAD

**Issue by afshin2003** [noflo/noflo#292]
Hi Guys,
I was wondering if somebody could provide me javascript equivalence of async component example which is stated on documentation section!

Appreciated,
Afshin

**Comment by bergie** [comment]
```javascript
var noflo = require('noflo');

exports.getComponent = function () {
  var c = new noflo.Component();
  c.description = 'This component does async stuff';
  c.inPorts.add('in', { datatype: 'object' });
  c.outPorts.add('out', { datatype: 'object' });
  c.outPorts.add('error', { datatype: 'object' });

  noflo.helpers.WirePattern(c, {
    in: 'in',
    out: 'out',
    async: true,
    forwardGroups: true
  }, function (data, groups, out, callback) {
    someAsyncFunction(data, function (err, result) {
      if (err) {
        return callback(err);
      }
      out.send(result);
      callback();
    });
  });

  return c;
};

**Comment by afshin2003** [comment]
Thank you so much!
BEST

**Comment by afshin2003** [comment]
Hi bergie,
Would you mind telling me how to define a component which does not have any input port? After I removed the definitions of 'in' port, it says 
<< uncaughtException [Error: no inPort named 'in'] >>

BEST
Afshin

**Comment by alfa256** [comment]
What are you trying to do Afshin? Having no input ports is not something
desirable in FBP. Also can you post your code with the explanation ?

**Comment by afshin2003** [comment]
Hi,
well, here is the thing,

I'm developing an IVR system based on noflo which is using FreeSWITCH as telephony platform. with proper configuration, freeswitch connects a control socket to an external program to manage telephony behavior. Here is noflo graphs come to play. As a starting component I have Inbound component which listen to a configurable port and for every new call attempt builds a connection object and sends it to the next stage. It's clear that by combining the listener function and Inbound component I don't need to any input port because it gets its input via socket. So as far as I understand, I need to have my own listener process and 
1) embed noflo graph into and inject connection objects to input port of Inbound component  or
2) inject call Ids to the external noflo process and let them connect to FreeSWITCH by themselves.

I'll appreciate If you could provide me a simple example. If you would like to have my draft code I'll post here for sure :)

Afshin
