### ISSUE TITLE
Exception: OUT Socket ID required

### ISSUE THREAD

**Issue by afshin2003** [noflo/noflo#293]
Hi Guys,

I have the following component in which 'out' port has defined addressable. Sending data in any forms over 'out' causes "Unhandled rejection Error: Menu1 OUT Socket ID required". Actually I'm not sure about the syntax of send method. I set port index in the second parameter. Any idea?

Appreciate
Afshin

/////////////////////////////////////////////////////////////////////////
var noflo = require('noflo')
  , freeswitch = require('./../lib/freeswitch');

exports.getComponent = function () {
  var fs = new freeswitch.Freeswitch(); 
  var c = new noflo.Component();

  c.description = 'This component creates a voice menu for the caller';
  c.inPorts.add('in', { datatype: 'object' });
  c.outPorts.add('out', { datatype: 'object', addressable: true });
  c.outPorts.add('error', { datatype: 'object' });

  noflo.helpers.WirePattern(c, {
    in : 'in',  
    out: 'out',
    async: true,
    forwardGroups: true
  }, function (data, groups, out, callback) {
    var conn = data.conn;
    fs.myMenu(conn, function(err) {
      if (err) { return callback(err); }
      out.send(data, 0);
          callback();
    });
  });
  return c;
};

**Comment by bergie** [comment]
With regular outports, you can just `send` to all connections at once. With addressable ports you need to provide a connection index

**Comment by afshin2003** [comment]
Hi Bergie,
Thanks for your support,

How I can do this? I have no idea :)

**Comment by afshin2003** [comment]
If you mean index in the graph json file, I've already done it!

{
  "properties": {
    "name": "Rightel IVR Payment"
  },
  "processes": {
    "Inbound": {
      "component": "freeswitch/inbound",
      "metadata": {}
    },
    "Greeting": {
      "component": "freeswitch/playback",
      "metadata": {
	    "voice": "ivr/tvedc-greeting.wav"
	  }
    },
    "Menu1": {
      "component": "freeswitch/autoattendant",
      "metadata": {}
    },
    "Hold": {
      "component": "freeswitch/hold",
      "metadata": {}
    }
  },
  "connections": [
    {
      "src": {
        "process": "Inbound",
        "port": "out"
      },
      "tgt": {
        "process": "Greeting",
        "port": "in"
      }
    },
	{
      "src": {
        "process": "Greeting",
        "port": "out"
      },
      "tgt": {
        "process": "Menu1",
        "port": "in"
      }
    },
	{
      "src": {
        "process": "Menu1",
        "port": "out",
        "index": 0
      },
      "tgt": {
        "process": "Hold",
        "port": "in"
      }
    }
  ],
  "inports" : {
    "inboundin" : {
	  "process": "Inbound",
	  "port": "in",
	  "metadata": {}
	}
  }
}

**Comment by bergie** [comment]
`out.send(data, 0);` seems correct. Interesting, that error should only happen if the provided `socketId` is `NULL`

**Comment by bergie** [comment]
OK, I tested that this works with regular ports, so seems this is a WirePattern issue. Ping @trustmaster

**Comment by bergie** [comment]
WirePattern is now using Process API internally, so this should be fixed.
