### ISSUE TITLE
grunt build failed: can't find remote for "jashkenas/underscore"

### ISSUE THREAD

**Issue by AxelVoitier** [noflo/noflo#355]
Hello,

Related to the issues I had building noflo-ui: https://github.com/noflo/noflo-ui/issues/510

grunt build of this component is failing:
```
# grunt build --force
Running "build" task

Running "coffee:libraries" (coffee) task
>> 20 files created.

Running "coffee:libraries_nodejs" (coffee) task
>> 1 files created.

Running "coffee:bin" (coffee) task
>> 1 files created.

Running "coffee:spec" (coffee) task
>> 14 files created.

Running "noflo_manifest:update" (noflo_manifest) task
File "package.json" updated.
File "component.json" updated.

Running "noflo_browser:build" (noflo_browser) task
install bergie/emitter@master
install jashkenas/underscore@master
install flowbased/fbp@master
Warning: failed to fetch https://raw.githubusercontent.com/jashkenas/underscore/master/component.json, got 404 "Not Found" Used --force, continuing.
>> Error: can't find remote for "jashkenas/underscore"
bergie/emitter complete
flowbased/fbp complete
```

This is because, recently, jashkenas/underscore removed its component.json file. See [this](https://github.com/jashkenas/underscore/commit/8f3d0507e885f64a05424fdc09a07cf77e2f676b) commit.
And jashkenas/underscore is [referenced](https://github.com/noflo/noflo/blob/master/component.json#L13) in noflo's component.json.

At least that is what I understand of this problem so far (I know nothing about developing with node's ecosystem ^^).

**Comment by jonnor** [comment]
noflo and all NoFlo component libraries which noflo-ui depends on have now been fixed. So noflo-ui builds again: https://travis-ci.org/noflo/noflo-ui/builds/101126378
