### ISSUE TITLE
Error in process-error does not contain stacktrace

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#369]
This when caught in for instance noflo-nodejs: https://github.com/noflo/noflo-nodejs/commit/5b8f44a18ec585859313fefb58ccfe953a594f85

This makes it near impossible to debug the problem.

**Comment by jonnor** [comment]
Hm, it could be that this particular Error had no stack because it came from C++ (native node.js module).

**Comment by jonnor** [comment]
No, when caught manually inside the component, it did have stack.

**Comment by bergie** [comment]
Seems like there isn't much we can do:

> This feature is non-standard and is not on a standards track.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack
