### ISSUE TITLE
Network/component start/stop notification

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#370]
A network should notify the runtime when it has finished processing with `stop` event as well as when it has started with `start` event. A network is considered as stopped when the in-flight process counter is `0`. Pending operations and broken components may prevent it from stopping correctly.

There are 2 common types of components in NoFlo:
- Regular components which activate, get input, do something, send output and deactivate
- Generator components which listen for external events, activate themselves, send output and keep listening for external events

For regular components the convention of notifying the network is the following:
- The runtime sends `activate` event to the network right before calling the `process` function.
- The `process` function is responsible for notifying the runtime and network of its status either by
  - Calling `send` or `resolve` callback with a map of output ports and the result values
  - Calling `done` callback if its output behavior is not so trivial
- Upon receiving such a call, the runtime sends `deactivate` to the network

Generator components: WIP

**Comment by bergie** [comment]
Needs to address #221 and #261

**Comment by bergie** [comment]
Also see #385

**Comment by bergie** [comment]
So, basics:

* There should be only a single `start` event emitted by the network per execution
* There should be only a single `end` event emitted by the network per execution
* Between the `start` and `end` events the network is considered to be "running"
* Execution starts by calling `network.start()`
* Execution ends either by calling `network.stop()` or when all components have finished processing
* No packets may be transmitted, and components may not do any work while network is not running

Information we have currently available:

* Socket status (`connected`, `disconnected`, packet count in buffer)
* Component processing functions (return state/callback): `c.process`, WirePattern callback, `AsyncComponent.doAsync`
* We have components that use one of the above, and also components that use the "pure" port API

**Comment by bergie** [comment]
@trustmaster regarding generator components, won't they work exactly the same way as "regular" components in this sense? They're anyway activated by an inbound packet (for example, a "bang") and so can use the `process` function. HTTP server as a "generator" example:

```coffeescript
c = new noflo.Component
c.inPorts.add 'start',
  datatype: 'int'
c.inPorts.add 'stop',
  datatype: 'int'
c.outPorts.add 'request',
  datatype: 'object'

c.servers = {}
c.process (input, output) ->
  if input.has 'start'
    # We start the server when we receive a port to listen for
    port = input.get 'start'
    return unless port.type is 'data'
    return output.sendDone new Error "Already listening to #{port.data}" if c.servers[port.data]
    c.servers[port.data] = http.createServer (req, res) ->
      # New requests are sent out with send but without calling done
      output.send
        request: req
    c.servers[port.data].listen port.data, (err) ->
      if err
        c.servers[port.data] = null
        output.sendDone err
        return
    c.servers[port.data].on 'close', ->
      c.servers[port.data] = null
      # Done for this processing function is called only when the server closes
      output.done()

  if input.has 'stop'
    port = input.get 'start'
    return unless port.type is 'data'
    return output.sendDone new Error "Not listening to #{port.data}" unless c.servers[port.data]
    c.servers[port.data].close (err) ->
      return output.sendDone err if err
      output.done()
```

**Comment by trustmaster** [comment]
@bergie yes, generators need to be ignited by a incoming packet at some point, the question is how they activate and deactivate on incoming data or requests.

E.g. an HTTP server just starts and sets its handlers, it doesn't keep being activated all the time. In the above example we could imitate that long-running behavior by calling `activate()` on `start` packet and `deactivate()` on stop.

Another example is a component reading data from a Node.js stream or listening for DOM events. It is likely to be activated and deactivated on every chunk/event. The runtime is more probably interested in stream `end` event though. And for DOM events I dunno.

**Comment by bergie** [comment]
@trustmaster I think a generator should be considered "active" when it is listening to some external stuff, and "deactivated" when it stops listening. Doesn't really matter whether we're talking about a network service, a stream reader, or even `setInterval`.

**Comment by bergie** [comment]
Here's a quick-and-dirty diagram of how the network states change:

![untitled diagram](https://cloud.githubusercontent.com/assets/3346/14327675/a17b8582-fc33-11e5-9826-a722b90913ce.png)

**Comment by jonnor** [comment]
@bergie how did you generate that diagram?

**Comment by bergie** [comment]
@jonnor manually :-)

**Comment by bergie** [comment]
Regarding component state, here's what the [Dataflow book](https://www.kickstarter.com/projects/1712125778/dataflow-and-reactive-programming-systems) says:

> A node can be in one of a few states:
* Not yet initiated: The initial state of all nodes
* Terminated: Signifies that nodes will never be activated again
* Active: The node is currently activated. This may be further subdivided into active-normal and active-suspended (active but waiting on an external event)
* Inactive: The node is not activated but it is not terminated

**Comment by trustmaster** [comment]
Key notes from a Slack discussion:

There are 2 sets of 2 events each emitted by components and their parent networks:

- `started` - a node has been initialized and started accepting packets
- `activated` - a node has started processing some packets
- `deactivated` - a node has finished processing current packets
- `stopped` - a node has no jobs queued and has stopped accepting and processing packets

For normal components, process function, `WirePattern`, or `AsyncComponent` `doAsync` handles the `activated`/`deactivated` automatically. Generators have to emit these themselves and should be provided with methods to send these events to parent network.

If a component sends a packet to its outport while the network isn't running or the component has earlier declared itself as `deactivated`, the packet should be dropped and the network should emit a `process-error`.

Long-running networks can `activate`/`deactivate` for many times during a single lifecycle. Their lifecycle is normally ended by calling `stop()` externally.

Batch networks (ran via `noflo-nodejs --batch`) should call `stop()` on themselves automatically after receiving `deactivated` event.

**Comment by bergie** [comment]
Regarding generators, here is a simple one that can be used as an example about the lifecycle notifications:

https://github.com/noflo/noflo-core/blob/97c365ad7c0b1e5211d4f93a1ca792df9e6db92b/components/RunInterval.coffee

**Comment by bergie** [comment]
@trustmaster is this fine now that #455 is merged?

**Comment by trustmaster** [comment]
@bergie #455 makes the Network emit correct events and require callbacks. Then it's up to runtime how to use them. If you think it's beyond scope of this issue, then feel free to close it.
