### ISSUE TITLE
Graph-walking tool to get list of components used in project

### ISSUE THREAD

**Issue by bergie** [noflo/noflo#378]
We need to implement a tool that loads a NoFlo graph, and walks down the subgraph tree to find all components utilized in this network.

This will be useful for:

* Compiling NoFlo project into "minimal" version that only includes components actually in use #157
* Tracking progress towards porting components to the 1.0 API #205

**Comment by jonnor** [comment]
Isn't this done now in fbp-mmanifest? If not, what more needs to be done?

**Comment by bergie** [comment]
@jonnor it is, yes. So I think mainly needs documentation.

**Comment by bergie** [comment]
Available as CLI tool and JS lib in fbp-manifest, as well as in grunt-noflo-lint.
