### ISSUE TITLE
When will 0.6.X drop?

### ISSUE THREAD

**Issue by jskrzypek** [noflo/noflo#383]
The IP stuff looks like an awesome addition to the whole noflo system. We want to incorporate it into what were doing with noflo, but we don't want to just pull from master and start hacking on top of it before you guys settle on something relatively stable. Do you have any idea of a timeline for when we can expect 0.6.X to be released on npm/github?

Thanks!

**Comment by bergie** [comment]
I think reasonably soon. @trustmaster is working on some things we still want to include related to #373
