### ISSUE TITLE
Buffers vs. rolled back transactions

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#405]
@aretecode came across this issue while running multiple requests through a NoFlo (0.5.x) graph using Knex.js transactions.

Let's omit the fact that NoFlo 0.5.x doesn't have request isolation baked in and focus just on buffers and rolled back transactions or other no-longer-valid packets.

So there's a graph that processes HTTP requests, starts a database transaction and uses it in several branches to do the job. Most of components use WirePattern which uses buffers to collect data from multiple inputs for processing.

Now imagine that there are 5 requests coming one after another with a short interval, 3 of them are valid, 2 of them are invalid and make the transaction to be rolled back at some point. At some component down the stream these transaction packets may form the following sequence in a buffer:

```
[ valid, rolledBack, valid, rolledBack, valid]
```

So the first request may be completed successfully, but the moment this component is activated to process 2nd request, the transaction is already rolled back. Thus it will crash with error and/or block subsequent request from being processed (depending on how error handling is implemented).

Transactions are of course a special case because transactions have global state and a component can check if a transaction is rolled back somewhere else or not. And with proper request isolation like `IP.scope` in place it wouldn't block subsequent requests. But the problem of discarded data is more generic:
- Many IPs can belong to the same request
- Concurrent processing and buffering may be quite intense in a graph
- Some requests fail at single point, while their packets are scattered in the graph and are queued in port buffers
- Other components are not aware that request is no longer valid and its data needs to be discarded
- Some packets end up in port buffers forever, because packets on other inputs will never arrive

So the questions we'd like to bring up here are:
1. When a request fails at some node, what's the correct way to tell other components that other packets for that request have to be discarded?
2. What's the correct way to collect garbage (i.e. incomplete tuples which never get processed)?

Earlier we discussed garbage collection vs. buffer limits and the decision was made towards just making buffers bounded instead of doing garbage collection. But this issue demonstrates that buffer bounds are not a silver bullet.

**Comment by jonnor** [comment]
Re 2:
Are rolled back transactions common, or do they only happen in error conditions or rare conflicts due to concurrency?
If so I'm tempted to say just let it float around until the process dies/is restarted.
Alternatively, when a scope 'is completed', ie it has produced results or errored - then one could maybe remove all unclaimed IPs belonging to that scope. But this requires a notion of network/execution completion beyond that of counting IPs.

**Comment by trustmaster** [comment]
@jonnor in that particular example it's common because a transaction gets rolled back e.g. if data validation fails. It's probably a bad design but the problem is wider than transactions in particular.

**Comment by jonnor** [comment]
How is this typically done in Node.js ?

**Comment by trustmaster** [comment]
@jonnor via a long callback chain or promise chain that returns or throws at some point, which is not very concurrency-friendly.

**Comment by trustmaster** [comment]
This is something that should be handled on application architecture level, not by the underlying runtime. E.g. [noflo-assembly](https://github.com/noflo/noflo-assembly) attempts to solve this problem alongside with other things.
