### ISSUE TITLE
Bracket forwarding

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#419]
We need to make it explicit about

- which input to forward brackets from
- to which output(s)
- if brackets are auto-collected on some port, it should ignore them on `input.get()`

**Comment by bergie** [comment]
This is roughly equivalent to WirePattern's `forwardGroups: true`, and is useful for map-style components where the original brackets are useful to forward.

**Comment by jonnor** [comment]
Can we please make this default for map-style components somehow?

**Comment by bergie** [comment]
Example where bracket forwarding is useful:

```fbp
SplitArray OUT -> IN SomeOperation OUT -> IN PacketsToArray
```

This is roughly equivalent to a Promisified version:

```coffeescript
Promise.map someArray, someOperation
.then (result) ->
```

**Comment by trustmaster** [comment]
Is there a definition for a map-style component?

**Comment by bergie** [comment]
A map-style component is something that generally:

* has a single input port (and maybe some control ports)
* has a single output port (and maybe `error`)
* sends a packet per each received packet

**Comment by jonnor** [comment]
Most are also deterministic and state-free.

**Comment by trustmaster** [comment]
That may be to fuzzy to infer automatically, so i'd vote for explicit yet convenient options.

**Comment by bergie** [comment]
Agreed that this should be an option. Something like:

```
c.process
  forwardBrackets: 'in'
, (input, output) ->
```

**Comment by trustmaster** [comment]
How about

```coffeescript
c.inPorts.add 'in',
  datatype: 'string'
  pickBrackets: true

#...

c.process (input, output) ->

  # ...
  output.sendWithBrackets
    out: something
```

**Comment by trustmaster** [comment]
or even

```coffeescript
c.inPorts.add 'in',
  datatype: 'string'
  pickBrackets: true
c.outPorts.add 'out',
  datatype: 'string'
  pushBrackets: true

c.process (input, output) ->
  # ...
  output.sendDone
    out: something
```

**Comment by jonnor** [comment]
```
  forwardBrackets:
    'in': 'out'
    'in': 'error'
```
This could be default, with 'in' being auto-detected to be first non-control inport, and 'out' to be the first outport.
If you don't want it, do `forwardBrackets: {}`, or set it to be complex config you want.

**Comment by jonnor** [comment]
The problem is how this interacts with async IP processing. Ordering wrt to the 'contained' IPs should be maintained for bracket IPs.

(aside, this is why I was so happy to see groups being on the IP object, and then dissapointed when all that went away, and we've effectively just renamed groups to brackets...)

**Comment by trustmaster** [comment]
I agree that we should once again thoughtful in our apps about what brackets are used for. They should only be used for substreams, not for tagging data with ids and metadata.

**Comment by trustmaster** [comment]
For example, here is a quicker way to add bracket forwarding to `ParseYaml`: https://gist.github.com/trustmaster/c7117776d2aab3a18fecffa7f44ae5ac

**Comment by jonnor** [comment]
Yes, hopefully we'll use it less now.
But for instance, what should the pattern be for a usecase like the following:

* Make an HTTP request to get a collection
* Fetch data over HTTP for each item in the collection
* For each data, do a couple different asyncronous work (maybe process using 3 different algorithms)
* When *all the work for one piece of data* is completed, write the combined results

This needs to be able to merge/collate based on which data a particular packet belongs to.
In NoFlo 0.6 we'd use groups for this. What do we do now?

**Comment by bergie** [comment]
@jonnor @trustmaster indeed, we should remove all "brackets as metadata" usage from components as we modernize (#410) them, and ensure it is only used for substream handling. But when it is used for substreams, it is pretty important to forward them, as otherwise many programs will have problems knowing when something is "complete"

**Comment by bergie** [comment]
Once this issue is resolved, we should document the new "best practices" around brackets and packet metadata, and update the "modernization" issue accordingly

**Comment by trustmaster** [comment]
> Example where bracket forwarding is useful:
> 
> ```
> SplitArray OUT -> IN SomeOperation OUT -> IN PacketsToArray
> ```
> 
> This is roughly equivalent to a Promisified version:
> 
> ```coffeescript
> Promise.map someArray, someOperation
> .then (result) ->
> ```

I think raw bracket forwarding is incorrect for this case, because maintaining the order of packets like `<, d, d, d, >` makes the whole operation act like `Promise.mapSeries` rather than `Promise.map`. If `SomeOperation` is supposed to be concurrent and stateless, then `SplitArray` and `PacketsToArray` should be replaced to a kind of `Map` and `Reduce` components, which would either create a dedicated scope for each collection, or tag and untag data. I'd see it like this:

1. `Map` splits the array and tags each packet with two properties: `collectionId`, `collectionLength`.
2. `SomeOperation` processes the data and forwards `collectionId` and `collectionLength` with the result IPs.
3. `Reduce` assembles the collection back.

**Comment by jonnor** [comment]
But the way we make components right now, `SomeOperation` will not forward `collectionId` and `collectionLength` with the IPs. To require each operation used with a `Map` / `Reduce` (or something similar) to be aware of the particular IP properties to pass seems at best tedious.

This is why I wanted map-style components to pass the input IP onwards, and just replace `.data` property with the result data. Then all metadata on the IP is preserved, without requiring knowledge of what other things are on the IP.

**Comment by trustmaster** [comment]
Here is another side effect of automatic bracket forwarding: it is only possible for asynchronous components that maintain output queue, or `ordered: true` in other words. Otherwise the order of bracket and data packets could be messed. If most elementary (or "map type") components are serialized in this way, this would imply a massive concurrency limitation. On the other hand, this is how both NoFlo and CFBP have been working so far: ordered by default.

I really like the @jonnor's idea of making map-style components modify the original IP instead of creating a new one. But it requires a slightly different convention for writing such components and probably some artificial way to enforce it.

**Comment by bergie** [comment]
One option is to do the following: We impose ordered mode when we receive an openBracket, until exiting bracket context.

Packets `A B < C D >` can come out as `A B < C D >`, `B A < C D >`, or `A < C D > B ` etc

If C and D get routed to different outports, we'll need to send brackets to both. So OUT would get `A B < C >` and ERROR would get `< D >`. So they still are "substreams" but the stream gets split to however many places packets from it get sent to.

For example if routers/SplitInSequence receives `< A B C D >` it would send to OUT[0] `< A C >` and to OUT[1] `< B D >`

**Comment by trustmaster** [comment]
Here is the case that got me blocked on bracket forwarding. Given a mapping as simple as

```coffeescript
forwardBrackets:
  in: [‘foo’, ‘bar’]
```

(which is from `in` to both `foo` and `bar`) and a fact that most components would like to send the output one way of the possible two, and they decide where to send and when inside the process function. The implementation i currently have automatically forwards brackets to both, but if the component only sends data to `foo` then `bar` gets empty brackets. There are 2 ways to fix it that i can think of:

1. Only send brackets if a process function sends something. This sounds right, but it has two side effects:
  - It would keep silent between output.sends, especially if sends are not on every activation
  - Closing brackets may arrive at the input after process activation and they would be pending until next activation (which may never come)
2. Detect and remove empty brackets from output buffers. This has the obvious side effect of not supporting empty streams.

Input is very welcomed on this dilemma.

Another question that results from the same mapping is a case where the component _actually wants_ to forward brackets to both outports at the same time.

And for those who wonder how i decided to handle mappings like

```coffeescript
forwardBrackets:
  foo: ['out']
  bar: ['out']
```

currently it would combine brackets from both `foo` and `bar` in the order they arrive. I don't know how right this approach is, but it's there.
