### ISSUE TITLE
Components in subdirectory not being loaded via ComponentLoader

### ISSUE THREAD

**Issue by JamesHagerman** [noflo/noflo#425]
Hi there,

In our project, we have multiple different types of components that we'd like to keep in separate subdirectories, something like:

```
./noflo-project/
./noflo-project/server.js
./noflo-project/package.json

./noflo-project/components/
./noflo-project/components/value.js
./noflo-project/components/utils/list.js
```

We have defined the components in the package.json file in this sort of format:

```
{
  "name": "noflo-project",
  "version": "0.0.1",
  "dependencies": {
    ...
  },
  "noflo": {
    "components": {
      "list": "components/utils/list.js",
      "value": "components/value.js"
    }
  }
}
```

The packages directly in the `components/` load correctly, but those in the subdirectory `utils/` do not.

This was working just fine on 0.5.22 but after we upgraded to 0.7.4 to grab some updates and fixes, our app is throwing errors that look like:

```
[Error: Component list not available with base /Users/username/noflo-project]
```

Is this a bug or expected behavior?

Thanks

**Comment by JamesHagerman** [comment]
I looked into this more and it looks as though this has something to do with the move to `fbp-manifest`.

The issue seems to be that the code `noflo-cache-preheat` calls out to inside `ComponentLoader` and `fbp-manifest` don't recurse into subdirectories correctly.

I think this is a bug with either `fbp-manifest/src/list.coffee` around line 26 or in `noflo/src/lib/nodesjs/ComponentLoader.coffee` on or around line 96

What is the correct solution to this issue?

**Comment by bergie** [comment]
The right way would be to make `fbp-manifest`'s NoFlo loader aware of subdirectories. Can you report a corresponding issue there?

**Comment by JamesHagerman** [comment]
On it! Thanks for the help!
