### ISSUE TITLE
Update WirePattern to speak IP objects correctly

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#429]
WirePattern has not been modified since IP objects were added and it is giving quite some problem when there are components that use the IP objects/Process API  and the old WirePattern components, e.g. having to send unnecessary bracket packets.

It also needs to be updated to support `scope` property.

**Comment by bergie** [comment]
This should be fine now @trustmaster ?

I think after #518 lands, I would consider starting to move at least the easier WirePattern cases to run Process API internally..
