### ISSUE TITLE
Add index support when sending output via Process API

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#441]
There should be a way to specify array port index when sending a single IP or a mapping via Process API `output` object.

**Comment by aretecode** [comment]
If sending single IPs, or multiple IPs with mapping, `IP.index` is used for the port index. https://github.com/noflo/noflo/blob/master/src/lib/OutPort.coffee#L59

**Comment by trustmaster** [comment]
Yes, this issue is mostly about specifying index when sending raw value.

**Comment by aretecode** [comment]
Why add another check every time you `send` just to support indexes when sending`IP`s supports it?

**Comment by trustmaster** [comment]
Adding index support to `send()` and `sendDone()` would complicate already complex object logic even more. So, instead we'd want to add `index` to `sendIP()` [here](https://github.com/noflo/noflo/blob/master/src/lib/Component.coffee#L674) and tell in the docs that if you need to send data to specific port index, you should do it by calling `sendIP()` for each packet:

```coffeescript
ip = new noflo.IP('data', 'fooobar')
output.sendIP 'out', ip, 0
output.sendIP 'out', ip, 3
```

**Comment by bergie** [comment]
The other option would be to utilize the [index notation helper](https://github.com/noflo/noflo/blob/master/src/lib/Ports.coffee#L78) we already have, so you could do:

```coffeescript
output.send 'out[2]', ip
```

**Comment by trustmaster** [comment]
Yes, that's a valid option as well.

**Comment by bergie** [comment]
In practice, sending with IP index has been fine. Closing.
