### ISSUE TITLE
Add a way to disable autoOrdering for a component

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#445]
Some components like `noflo-core/DisconnectAfterPacket` would like to manipulate the output stream in their own way rather than `Component` maintaining the order of the brackets for them. For those there should be a way to set `component.autoOrdering = false`.

**Comment by bergie** [comment]
Current workaround is to set `c.autoOrdering = false` in the Process API callback, but a better fix would be to automatically enable auto-ordering only if it is not set (so, `NULL` default)
