### ISSUE TITLE
Process API: Dropping a packet causes an error

### ISSUE THREAD

**Issue by bergie** [noflo/noflo#446]
When a component drops a packet in the process function, this causes an error:

```
TypeError: Cannot read property 'event' of undefined
    at InternalSocket.handleSocketEvent (node_modules/noflo/lib/InternalSocket.js:192:40)
    at InternalSocket.send (node_modules/noflo/lib/InternalSocket.js:58:19)
    at Context.<anonymous> (spec/Drop.coffee:31:11)
```

Example implementation:

```
c.process (input, output) ->
  data = input.get 'in'
  data.drop()
  output.done()
```

https://github.com/noflo/noflo-core/blob/37f01dab3a4d77fa6c00bfc673d708491b35782f/components/Drop.coffee

**Comment by trustmaster** [comment]
Here is what's happening here:

1. `process` function gets called and it disposes the packet before returning control
2. legacy `data` event handler is called for the same object but it is already destroyed and it crashes
