### ISSUE TITLE
Add support for default port in output.send in process api

### ISSUE THREAD

**Issue by aretecode** [noflo/noflo#450]
Currently if we have a component with just one output defined (aside from error) for example

```
noflo = require 'noflo'

exports.getComponent = ->
  c = new noflo.Component

  c.outPorts = new noflo.OutPorts
    out:
      datatype: 'object'
    error:
      datatype: 'all'
```

and we want to send out of the out port
```
  c.process (input, output) ->
    output.send out: ''
```

instead we should have a default which would send to the one other port aside from error (after it checks to see if is an erorr)
```
  c.process (input, output) ->
    output.send ''
```

**Comment by bergie** [comment]
Fixed via #451
