### ISSUE TITLE
Outmost brackets get swallowed by brackets-to-events adapter

### ISSUE THREAD

**Issue by trustmaster** [noflo/noflo#462]
Considering the flow like this: `Sender -> Receiver` where `Sender` uses the Process API and `Receiver` uses the old events, there's a problem when the Sender sends a substream. In the new API the connect/disconnect are not required, so outmost brackets really mean that they contain a substream. But in the current `ipToLegacy` adapter they get swallowed into `connect` and `disconnect`, so the Receiver does not receive the expected `beginGroup` and `endGroup`.

A potential solution to this is to change the `ipToLegacy` adapter, and instead of treating outmost brackets as `connect` and `disconnect`, it should consider them as `beginGroup` and `endGroup` and wrap them by adding `connect` and `disconnect` if there is need to: `connect` before the first `ip` in the substream and `disconnect` after the last bracket in the substream, just like it does for single `ip`s.

**Comment by bergie** [comment]
#463 contains some red tests for this
