### ISSUE TITLE
Process API: Catch component exceptions and send to error

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#466]
Right now would (probably?) go to `process-error` event, which cannot be caught in the FBP graph/program.

This is similar to how promises for instance 'normalizes' also unexpected exceptions to become a Promise.rejection

**Comment by trustmaster** [comment]
Already doing this in this branch: https://github.com/trustmaster/noflo/blob/network_states/src/lib/Component.coffee#L141

**Comment by bergie** [comment]
Fixed via #455
