### ISSUE TITLE
WirePattern adds group on error outports

### ISSUE THREAD

**Issue by automata** [noflo/noflo#485]
WirePattern automatically adds component name as the outmost group on error outports. Adding an outmost group to groups forwarded by error outports can cause unexpected behaviours on NoFlo graphs expecting some group level/order.

[This is the test](https://github.com/automata/noflo/commit/310439d1599cc271ee52a0f3e36aa9181758205b) that motivated the discussion (and [its output](https://travis-ci.org/automata/noflo/jobs/142779504#L721)). It was originally conceived for another issue involving groups duplication: https://github.com/noflo/noflo/issues/269.

**Comment by bergie** [comment]
With #526 this should only happen when providing `name` for the WirePattern
