### ISSUE TITLE
input.getData should get data IPs

### ISSUE THREAD

**Issue by aretecode** [noflo/noflo#487]
`input.getData` should return the value of the `.data` property from the first `data` `IP` from the `buffer` of the port(s) being passed as arguments.

1) Should it remove the `openBracket` from the `buffer`?

2) Should it remove the `closeBracket` from the `buffer`, if the next packet in the `buffer` is a `closeBracket`? Or should it remove `closeBracket` and return the value of the `.data` property of `closeBracket` when `input.getData` is called again?

Consider a situation where a component is sent `< data >`, the handler calls `input.getData` and removes the `openBracket` and `data`, then `< data >` is sent again and the handler does the same thing. Then the `buffer` is left with two `closeBracket`s.

3) What about nested streams where there are two+ `openBrackets` before `data`?

@trustmaster @bergie @jonnor

**Comment by trustmaster** [comment]
If we are all agreed to change `input.getData()` semantics so that it only works with `data` IPs (while it currently works with `.data` of brackets too which is legit), then it should consume all the brackets up to the closest data packet, e.g.:

```coffeescript
ip = input.buffer.get(portName).shift() until ip.type is 'data'
```

Then it would consume&skip all the brackets including the closing ones. Some closing brackets may be left until next `data` arrives, but it's ok since they would be cleared then.

**Comment by aretecode** [comment]
@trustmaster, wouldn't that also shift if it was only data and no brackets? Or if your precondition `return unless input.has 'in', (ip) -> ip.type is 'data'` then it will trigger before there is a `closeBracket`. In my implementation here https://github.com/noflo/noflo/pull/488/files it will `get` until there is `data` (removing the brackets up to it), then it checks if there are any `data` packets after it, if there is not, it removes the following brackets.

**Comment by trustmaster** [comment]
@aretecode that line compiles to a normal `while (...) { ... }` loop. But of course you need one initial buffer shift before that loop.

I mean there's no need to do a look-behind search and remove brackets as they will be dropped before next data anyways.

**Comment by trustmaster** [comment]
But your code is just OK.

**Comment by bergie** [comment]
Should be fine now. We also have a `input.hasData` convenience method
