### ISSUE TITLE
IP Object duck typing is leaky

### ISSUE THREAD

**Issue by bergie** [noflo/noflo#491]
In noflo-ui we're sending a packet that is an object that contains a `data` key. That gets converted in NoFlo to an IP object containing only the contents of the `data` key instead of IP object containing the whole original object.

This is the reason why we get noflo/noflo-ui#600

**Comment by trustmaster** [comment]
@bergie is it possible to set IP `.type` property in noflo-ui as well? Because without that neither duck typing nor brackets can work.

**Comment by bergie** [comment]
@trustmaster the problem here is that in noflo-ui we send packet objects through the graph, and they suspiciously resemble an IP object even though that is not the intent.

See noflo/noflo-runtime#88

**Comment by trustmaster** [comment]
Any ideas at what stage it may be happening? I can't recall any place where `.data` is used to detect packet type, the actual check is https://github.com/noflo/noflo/blob/master/src/lib/IP.coffee#L13

**Comment by bergie** [comment]
@trustmaster here is the original `outport.send` command: https://github.com/noflo/noflo-runtime/blob/2afb74aacb345e6a2dcf55a90b6db44958e781b3/components/ListenNetwork.coffee#L43

As you can see the payload is an object that contains `type: 'data'`

**Comment by trustmaster** [comment]
@bergie thanks, got it. We can try to switch to strict typing then.
