### ISSUE TITLE
Typescript port ?

### ISSUE THREAD

**Issue by jomeier** [noflo/noflo#504]
Hi,

are you interested in a typescript port of noflo? 

I think it shouldn't be that hard if we would use a transpiler like "coffee-script-to-typescript".

The question would also be: where to host and maintain it?

Best regards,

Josef

**Comment by trustmaster** [comment]
@jomeier is it really required to port it? NoFlo supports components in any language that compiles to JavaScript, even if the library itself is written in CofeeScript it doesn't mean user code has to.

**Comment by jomeier** [comment]
@trustmaster 
For the components you are right. But if we want to expand noflo I think it would be good to have an alternative to coffeescript as its code base. In my opinion typescript would be a good choice. 

Would that be a fork of the original project or where could we host a typescript version?

**Comment by jonnor** [comment]
What benefits would it have? 

Maintaining two implementations of a code base  is a lot of extra work, large risk of incompatibilities, and user confusion (should I use this or that version?).

**Comment by jomeier** [comment]
@jonnor:
I fully understand this argument. But in my opinion typescript is more common nowadays than coffeescript. It's more like C# or Java. This could attract more people for this great project.

But I understand the problem of two code bases.

**Comment by jonnor** [comment]
If people interested in Typescript would like to contribute to NoFlo I would recommend adding Typeaceip

**Comment by jomeier** [comment]
Where can I put documentation for that? Here?

**Comment by jonnor** [comment]
Ideally make a PR that puts it under documentation on noflojs.org, then it will appear on the main website>
https://github.com/noflo/noflo.github.io/tree/master/documentation/_posts

**Comment by jimmywarting** [comment]
I like the idea of a typed language. but i don't like precompiler so i don't like typescript/coffescript.
I like to develop on the latest environment for node and chrome without it having to go through a compiling step that adds time. Only time i use a compiler is when i publish it, Then i run it through babel to make it backward compitable.

for me javascript is javascript that can be executed without it having to go through some compile step.

So for me typescirpt is the new coffeescript that isn't the standard and doesn't work without a compiler therefore its something i hate.

Technologies that have competing spec / community driven development have a history of failing; take Flash & SilverLight for example

----

So i would vote for ES6/7

**Comment by jomeier** [comment]
Typescript is very similar to ES6 but supports types.

The result is Javascript5/6. So its not comparable to Flash or Silverlight.

**Comment by aretecode** [comment]
@jimmywarting I also think es6/7
@jomeier you can use flowtypes with es6/7 with only the building step, or you can simply annotate with Native Functions as in `function(fn = Function, str = String)`

**Comment by jimmywarting** [comment]
@jomeier i'm not talking about the difference in syntax or that the result is in es5/6, I'm compering it with flash/silverlight cuz i think it will eventually die out like the rest since ppl will stop maintaining it and that It's always going to be one/two step behind thos making ppl leave the typescript syntax. Who knows maybe one day we will have types in javascript but it won't look like typescript syntax. have fun updating. 

Once we get async for loop and other new syntax feature you are going to wish you had vanilla javascript instead cuz you would always have to wait for typescript to adopt to the new standard

**Comment by bergie** [comment]
BTW, it is possible to compile CoffeeScript to ES6 now as well: http://coffeescript.org/v2/

Regarding TypeScript, I agree with @trustmaster and @jonnor that porting NoFlo is unlikely to bring big benefits right now. However, what might be interesting would be to add [TypeScript declarations](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) for the NoFlo API.

This way we wouldn't need to change NoFlo core, but TypeScript developers would still benefit from the types being declared and available.
