### ISSUE TITLE
How to update/delete an existing graph?

### ISSUE THREAD

**Issue by jomeier** [noflo/noflo#506]
Hi,

I wrote a UI for noflo. The UI connects to the noflo server through websockests (I use noflo-nodejs).

If I load a graph through the fbp remote protocol and start the network, everything is alright.

If I stop the network, do a graph->clear and load a different graph (replace the fomer one) with the same graph name and start the network it seems as if the old graph starts. My new graph (updated IIPs, ...) is ignored.

If I choose a different graph name for the new graph, it will be accepted by the noflo engine, I can start it and it works like expected. But I want to replace graphs with new content and use the same graph name.

Does someone have an advice for me? Whats the right procedure to replace a graph through the fbp protocol?

Best regards, 

Josef

**Comment by jomeier** [comment]
If I choose a different graph name for the new graph, it will be accepted by the noflo engine and I can start it. 

But it seems strange to me that I have to change the graph's name everytime I want to load a new graph or update the current one.

Does someone have an advice for me?

**Comment by jonnor** [comment]
Right now you would have to tear it down explicitly, by removing all existing nodes, then adding your changes.

I agree that there should be a destroy/remove message in the FBP protocol, which would remove a graph.

**Comment by jomeier** [comment]
There's another topic on that: If the UI restarts, it has no knowledge about running graphs, cause there's no fbp protocol command to get the structure of a graph out of the server.

It would be nice to have that.

**Comment by jonnor** [comment]
NoFlo UI uses `component:source` for that, and basically all runtimes implement that. Even though it should just use the normal graph building parts: https://github.com/noflo/noflo-ui/issues/390

**Comment by jomeier** [comment]
My use case is that the graph will be created dynamically through the UI. I use noflo-nodejs with the fbp protocol.

There is no source I could load into the UI. 

A methid would be great to get the graoh from the server in JSON format.

**Comment by jonnor** [comment]
That is exactly how it is used, see the linked issue.

**Comment by jomeier** [comment]
OMG. That's great! That's a hidden feature :-) 

The documentation of the fbp protocol 
should mention that "name" is not only the name of a component but also the name of a graph?
