### ISSUE TITLE
How does a process get it's identifier?

### ISSUE THREAD

**Issue by jomeier** [noflo/noflo#507]
Hi,

Inside of one of my components I like to get the identifier of it's running instance (=process). Is this possible?

Best regards,

Josef

**Comment by jonnor** [comment]
Looking at the Component code there does not seem to be an easy way.

Why do you want to do this? It is generally bad practice. A component should ideally not care about anything in the outside world that is not passed on its input ports. This includes the instance name.

**Comment by jomeier** [comment]
My idea is that each instance of my component connects to a websocket server which sends the traffic to the User Interface. In the user interface I must create a relationship between the UI representation and the underlying processes. Without getting the identifier I can't connect the ui node symbol with my process.

For sure I could add an IIP to each UI node but ... seems like a workaround.

**Comment by jonnor** [comment]
So you're building a UI for your program? And each process which has UI representation talks to the WebSocket server?

Some alternate approaches would be:

### Dedicated WebSocket sender
Have a dedicated component, with a single instance, for sending to webUI. Use one input port, with a descriptive name, per piece of data you want to send. Connect these ports to the outports of the processes which produce the data. Benefits:
* Only one component needs to know about UI/WebSocket, the rest of the program remains agnostic.
* Encourages that all state/data needed for the UI is sent on outports of components. This is good practice for future extensability and for testability.
 
### Use FBP runtime protocol
Don't put any WebSocket code into components/network. Instead mount the graph in a runtime, like `noflo-nodejs`, and let the UI connect to the WebSocket interface and talk on the FBP runtime protocol.
Using `network:data` packets one can follow changes of data on ports.

Benefits:
* The entire program is agnostic to the UI/WebSocket. Can add UIs to existing programs without modifying them.

Note that I don't do a lot of UI programming with NoFlo/FBP, so take these more as ideas than canon :)

**Comment by jomeier** [comment]
Ok. Cool. Thanks for your ideas. Do you know any examples in using runtime:packet or network:data? Can this be used to see the live status of the graph?

**Comment by bergie** [comment]
The component get its node name via `this.nodeId`, which NoFlo Network sets after instantiation.

**Comment by bergie** [comment]
@jomeier here are the schemas for those:

* https://github.com/flowbased/fbp-protocol/blob/master/schema/yaml/network.yml#L245
* https://github.com/flowbased/fbp-protocol/blob/master/schema/yaml/runtime.yml#L35

And yes, those can be used to see the live status. See for example Flowhub
