### ISSUE TITLE
How can I trigger the system to load a new component so it's available to the component:list command?

### ISSUE THREAD

**Issue by jomeier** [noflo/noflo#510]
How can I trigger the system to load a new component so it's available to the component:list command and can be added to the graph without restarting the noflo server?

Thanks,

Josef

**Comment by bergie** [comment]
Look at the `setSource` method on component loader.

**Comment by jonnor** [comment]
Or the `component:source` message in the FBP runtime protocol. http://flowbased.github.io/fbp-protocol#source

**Comment by jomeier** [comment]
Thanks for the advice!
