### ISSUE TITLE
How to get a list of all dynamically created graphs through the fbp protocol?

### ISSUE THREAD

**Issue by jomeier** [noflo/noflo#511]
Hi,

if the UI connects to a running runtime and knows nothing about formerly created graphs, how can it get a list of all all graphs which were dynamically created through the fbp protocol?

Thanks,

Josef

**Comment by jomeier** [comment]
I created a pull request for a list command. Maybe someone can check that?

**Comment by bergie** [comment]
This is more properly tracked in flowbased/fbp-protocol#25
