### ISSUE TITLE
Add generic metadata field to components

### ISSUE THREAD

**Issue by jomeier** [noflo/noflo#512]
Hi,

it would be great if I could add my own metadata to a component and to each port.

This would be useful if for instance I want to choose a graphical representation of the data carried in a component in the UI.

Example:
.... description:"...",
metadata: '{ "viewer":"griddata", .... }

The UI would do a component:list over the fbp protocol, get this metadata 'viewer' and draw a UI element which shows the components/processes data in a 2d grid.

The metadata should carry a JSON string which can be set completely free by the user.

At the moment I put a JSON string with metadata in the description field. But this is only a temporary solution.

Is this possible ?

Thanks,

Josef

**Comment by jonnor** [comment]
It is defined for nodes, connections and exported ports in the graph, but not for components or component ports it seems. 
What kind of data do you want/need in there? 

Need an issue/PR on the protocol spec, 
https://github.com/flowbased/fbp-protocol
and implement it in noflo/noflo-runtime-base

**Comment by jomeier** [comment]
The idea is to define a field 'metadata' with the datatype Object which can contain anything which is needed to describe the component in an abstract way. We could for instance put describing tags inside which would help to sort/categorize/filter the components in the UI.

**Comment by bergie** [comment]
More properly tracked in flowbased/fbp-protocol#26
