### ISSUE TITLE
Split Graph code to dedicated library

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#517]
Wanted for use [in the-graph](https://github.com/flowhub/the-graph/issues/314) (which is not NoFlo-specific), and possibly [for MicroFlo](https://github.com/microflo/microflo/issues/42)

**Comment by jonnor** [comment]
I think that the Journal code should go with it, as that is also separate from the runtime-aspects, and only depends on Graph. And is used in non-NoFlo-specfic places like Flowhub.

**Comment by bergie** [comment]
We might want to move the graph schemas in the same place as well: https://github.com/flowbased/fbp/tree/master/schemata

**Comment by jonnor** [comment]
@bergie there is not much point to that, it is fine where it is?

**Comment by jonnor** [comment]
In fact the thing discussed here (lets call it `fbp-graph`) will likely depend on `fbp`, for parsing the DSL. So it would be problematic (circular) if `fbp` had to depend on `fbp-graph` in order to make use of the schema.

**Comment by bergie** [comment]
Here we go: https://github.com/flowbased/fbp-graph

**Comment by jonnor** [comment]
@bergie nice. Will you make a PR which uses that library in NoFlo? Otherwise the two will diverge very quickly...

**Comment by bergie** [comment]
@jonnor yup, #519
