### ISSUE TITLE
Is it possible to use noflo without flowhub?

### ISSUE THREAD

**Issue by justinmchase** [noflo/noflo#525]
I'm reading the getting [started documents](http://docs.flowhub.io/getting-started-node/) and this is making me wary:

> Connect your server to Flowhub
> The Flowhub user interface communicates with your server-side NoFlo instance over WebSockets.

I'm not going to really want my server to be connected to a 3rd party like this so I'm wondering if there is a way to run a flow disconnected? What is the purpose of the flowhub server and why would I want to connect to it?

**Comment by aretecode** [comment]
@justinmchase noflo does not require flowhub, flowhub is service that allows you to run noflo more easily and create graphs visually. I'm sure @bergie & @jonnor will be able to explain it better.


this is an example program that uses noflo without flowhub
https://github.com/aretecode/canadianness

and this is the documentation (this page in particular is for running it)
https://aretecode.github.io/noflo.github.io/projects/embedding/

**Comment by justinmchase** [comment]
I see so what you're saying is you just write an app with `noflo` package and then just run it like normal?

The thing throwing me off is the first step says to use 
> 1) ```noflo-nodejs --debug graphs/Canadianness.fbp```

But then the `nofolo-nodejs -h` command has:
>   --register          Register the runtime with Flowhub  [boolean] [default: true]

If I download the sample and do `npm install; npm start` it gives me an error about flowhub registration.

The default demo video on https://aretecode.github.io/noflo.github.io/documentation/ shows the speaker just running his graph via `noflo graphs/Main.fbp`... but when I do that it says its been deprecated and to use the other tool :(

Perhaps I'll eventually figure out that I want it connected to flowhub and all of that but for now I just want it all to run locally, in process. I think that part of the problem is that I'm not sure what flowhub is doing, I'm not sure why its part of the equation at all frankly.

**Comment by aretecode** [comment]
@justinmchase in that example project, just run `coffee index.coffee`

**Comment by jonnor** [comment]
Flowhub is an IDE. It's an alternative to using your text editor + terminal. Has graph/component editing tools (incl live programming), debugging support etc. 

The integration in noflo-nodejs is for discovery. It is opt-out, but should be opt-in:  https://github.com/noflo/noflo-nodejs/issues/45

**Comment by justinmchase** [comment]
@jonnor Thanks. I'll look into it a little more.
