### ISSUE TITLE
Cleaning up a done graph

### ISSUE THREAD

**Issue by afshin2003** [noflo/noflo#533]
Hi Guys,
I was wondering if I could know that shutting down a graph causes it be disposed by GC or not? I do not keep a reference of after I call its shutdown method. I use ComponentLoader to load and start the graph.

Best,
Afshin

**Comment by bergie** [comment]
Shutdown doesn't drop the graph reference, since typically graphs can be restarted as needed. However, if you drop the reference to the NoFlo network, then it should get garbage collected eventually

**Comment by afshin2003** [comment]
Hi Bergie,
Appreciated your rapid reply. Actually I drop my reference to the used graph but I keep my reference to the loader which loaded my graph. Does not it keep a reference to the already loaded graph? I am asking this because I have memory issue!

Afshin

**Comment by bergie** [comment]
@afshin2003 no, loader doesn't keep instance references, only the list of components available.

**Comment by afshin2003** [comment]
I got your point. Meanwhile I'm searching to find the God damn reference, would you tell me that shutting down the graph has the same functionality to stopping the network? I get network object from the graph!

**Comment by jonnor** [comment]
What do you mean "shutting down the graph"? There is no shutdown/stop for a graph (nor is there a start)

**Comment by afshin2003** [comment]
@jonnor I use shutdown method of the return instance of ComponentLoader's load method. I suppose the return object is a graph object! Isn't it?

**Comment by jonnor** [comment]
It is a `Component`. Which may be a direct instance/subclass if the thing is defined in code. Or if the loaded thing is a graph, then its a `noflo.components.Graph` instance (which subclasses `Component`). This is different from a `noflo.Graph` (which is just a description of a graph, doesnt/cannot be started).

And to answer the questions. Yes, `component.shutdown` for a subgraph causes `this.network.stop`. Looking at the code, it does not unset/unreference `this.network` though...

**Comment by afshin2003** [comment]
Ok, I switched to network.stop() for shutting down. So if I don't keep any reference to graph / network, do you expect that it is collected by the GC?

**Comment by jonnor** [comment]
Yes. There is at least one webservice which creates a new Graph instance per HTTP request, and I have not heard of any such problems there.

If you see something else will probably need a small executable example of the problem to be able to help. Btw, Chrome devtools heap debugger can be very helpful for checking memory issues. Can attach to the built-in Node.js debugger

**Comment by afshin2003** [comment]
So so much thanks!

**Comment by bergie** [comment]
OK, sounds like this one is resolved. Please reopen if there are still issues.
