### ISSUE TITLE
Integrate Flowtrace

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#536]
Code is currently in https://github.com/noflo/noflo-runtime-base
However, people don't always use a runtime, in which case they don't have the code available. And for embedding API #516 it would also be very desirable.

**Comment by 0fork** [comment]
Does this work out-of-the-box or is there some way to get flowtrace working right now?

I'm currently using asCallback() to run graphs as embedded but I'm having some challenges debugging graphs and components. There was initial parameter trace suggested at https://github.com/noflo/noflo/issues/516 but at least based on the code I'm assuming this wasn't implemented in the end?

**Comment by jonnor** [comment]
No, this has not been implemented yet, which is why this issue is still open.

The [code in noflo-runtime-base](https://github.com/noflo/noflo-runtime-base/blob/master/src/trace.coffee#L102) has an API, you can try to use that. Looking at the implementation will basically show what mechanisms NoFlo exposes that can be used. Note the major limitation of not collecting from subgraphs, https://github.com/noflo/noflo-runtime-base/issues/32

**Comment by 0fork** [comment]
Thanks @jonnor. Too bad that my graphs are mainly composed of subgraphs ;)
