### ISSUE TITLE
Can't stop runtime from UI

### ISSUE THREAD

**Issue by enib29** [noflo/noflo#542]
Hi!

I'm using noflo-ui with noflo-nodejs as runtime but when my graph is running, I'm not able to stop it... There is some asynchronous components (dealing with remote things), so not all of the component call their callback() function.

And it seems to be the problem. Because if I call the callback() at start of each async component, the run finished immediately. 

But that's not the expected behavior... Is there a way to force the graph to stop ? I checked that I have the "stop payload" in websocket traffic and it is there.

I browsed a long time each variable accessible like noflo... to find an stop event to listen but I failed to find that.

Do you have a solution about my problem? Because it's a bit weird because I know a lot of people use async component with noflo.

Thank you,

**Comment by enib29** [comment]
It seems while I was browsing issues I find the solution with one of your example @bergie : 
https://github.com/noflo/noflo-core/blob/97c365ad7c0b1e5211d4f93a1ca792df9e6db92b/components/RunInterval.coffee

So now I'm using the shutdown function : 
`    c.shutdown = (callback) => {
        // Do anything to stop async connection...
        callback();
    };`

And everything seems to work! It was hard to find it should be that, but should it be like that?

Please tell me if I'm doing wrong, I try to do my best :) 

Thanks

**Comment by bergie** [comment]
WirePattern is the legacy way, and the [process API](http://bergie.iki.fi/blog/noflo-process-api/) is the new recommended way. As a matter of fact, in NoFlo 0.8 WirePattern just sets up Process API internally.

You can find documentation on the component lifecycle in https://noflojs.org/documentation/components/#component-lifecycle

In 0.8, I'd recommend providing `setUp` and `tearDown` functions for components that need them instead of overriding `shutdown`.

BTW, if you're wondering which component(s) keep your network running, you can get a list of them with the `network.getActiveProcesses()` method.

**Comment by enib29** [comment]
Thanks for the advice!

I didn't find a way to access the current network variable? I just have access to noflo and the current component variable. Also, I browse their properties but I didn't see the current network.

I just saw the class noflo.Network to create a new one. Where can I find the network instance please?


PS: I'm handling and processing data separately for each port of a component with : 
`    c.inPorts.[in/in2/...].on('data', function (data) {`

Is there a way to activate the component with that or is this way totally far away from the right noflo guidelines?

Initially I planned to do a if statement in the process function but I noticed that if I put a parameter manually within noflo-ui (let's say port 1 value equals 5), the process can getData on it just once. I mean, if the port 2 received data, the process function will be triggered but without data on port 1 (while it's a data entered by hand).

The only solution found is to keep aside the value received in a persistant variable. But it seems really complicated no? I missed a better way?

**Comment by bergie** [comment]
@enib29 you can do per-port data processing also with Process API. Something like:

```coffeescript
c.process (input, output) ->
  if input.hasData('in2')
    data = input.getData('in2')
    # Do something, send outputs, then
    output.done()
    return
  if input.hasData('in3')
   # ....
```

If you want to keep the latest packet from a given port, you have two options:

1. Store it to component state and add appropriate `tearDown` logic to remove at network stop
2. Set the port you want to retain latest from to `control: true`. Control ports keep the latest packet and allow you to `getData` it multiple times
