### ISSUE TITLE
get supported by CTDConverter

### ISSUE THREAD

**Issue by jibe-b** [noflo/noflo#557]
I opened a feature request to ask for NoFlo support in CTDConverter

https://github.com/WorkflowConversion/CTDConverter/issues/32

**Comment by bergie** [comment]
@jibe-b thanks! What would be needed? The available components in a NoFlo installation can be discovered using the [fbp-manifest](https://www.npmjs.com/package/fbp) tool (which also supports other FBP systems).

**Comment by bergie** [comment]
Closing the issue NoFlo-side, subscribed to the upstream one.
