### ISSUE TITLE
Support for inline FBP/parsed JSON in asCallback()

### ISSUE THREAD

**Issue by 0fork** [noflo/noflo#582]
_This is a feature request that came from me trying to implement noflo with dynamic graphs into existing browser app and not being overly eager to refactor the build process._

Currently asCallback supports components & graphs only from files. It would be very useful to be able to pass either inline FBP or parsed JSON to asCallback. It would allow much faster prototyping and overall onboarding with FBP style of doing things.

According to my discussion with bergie in Twitter, "this shouldn't be hard to do" ;)

**Comment by bergie** [comment]
Docs in https://github.com/noflo/noflo.github.io/pull/76
