### ISSUE TITLE
Infer component metadata from JS function

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#590]
A lot of times I have a component as a plain JavaScript function, and then have the component call this function. I like to write this kind of style even for new components, as it makes the 'business logic' of the component very clear. 

When doing this one needs to create in/out ports that match the function, and a process function that calls the inner JS function. This is pretty mechanical, so maybe it could be provided by NoFlo?

Original component code

```
const noflo = require('noflo');

function apiUrl(tenant, username, password, token, base) {
  ....
  return { foo: 'bar' };
}

exports.getComponent = () => {
  const c = new noflo.Component();
  c.description = 'Parse';
  c.icon = 'file';

  c.inPorts.add('username', { datatype: 'string' });
  c.inPorts.add('password', { datatype: 'string' });
  c.inPorts.add('tenant', { datatype: 'string' });
  c.inPorts.add('token', { datatype: 'string' });
  c.outPorts.add('out', { datatype: 'string' });
  c.outPorts.add('error', { datatype: 'object' });

  c.process(((input, output) => {
    const ports = [ 'username', 'password', 'tenant', 'token' ];
    if (!input.hasData(ports) {
      return;
    }
    const username, password, tenant, token = input.getData(ports);
    const url = apiUrl(tenant, username, password, token);
    output.sendDone({
      out: url
    });
  });

  return c;
}
```

With inferred metadata
```
const noflo = require('noflo');

function apiUrl(tenant, username, password, token, base) {
  ....
  return { foo: 'bar' };
}

exports.getComponent = () => {
  const c = new noflo.Component();
  c.description = 'Parse';
  c.icon = 'file';
 
  noflo.component.infer(c, apiUrl);

  return c;
}
```

Those not used to NoFlo (but know JavaScript) might find this style extra welcoming.

**Comment by bergie** [comment]
Might be nice to call this `asComponent`, as it is basically the opposite of `asCallback`.

Cases to handle:

* Basic synchronous function (return value sent to `out`, thrown error sent to `error`)
* Function returning a Promise (resolved sent to `out`, failed sent to `error`)
* Function that has a `callback` as last argument (given `(err, out) =>` function)

The `asComponent` function should return a component instance. As the second argument one could supply an `options` object for things like icon, description, list of control ports, etc.

Then it can be as easy as:

```javascript
const foo = require('some-library');
const noflo = require('noflo');
module.exports = noflo.asComponent(foo, {
   description: 'Do foo',
});
```
