### ISSUE TITLE
asComponent breaks with get-function-params 2.0.5

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo#614]
Typical error is `Port names can only contain lowercase alphanumeric characters and underscores. 'cors){  return new bigiot.consumer(id' not allowed`

One of the argument names contains the body of the function, which is obviously wrong. Happens for a range of functions.

Commented upstream https://github.com/renolc/get-function-params/issues/4

**Comment by bergie** [comment]
Seems to be fixed now?
