### ISSUE TITLE
How to know when all component processes have stopped or deactivate on a network.

### ISSUE THREAD

**Issue by dallen66** [noflo/noflo#623]
I want to know when all process have stopped or deactivate on a network.

On each component I can listen for an event with 
``` javascript
c.on('deactivate', function (load){
     console.log("deactivate");
})
```
Is there a event available on the network level

**Comment by bergie** [comment]
Yes, use:

```javascript
network.on('end', () => {
  console.log('all processes have finished!');
});
```

There is also the `network.getActiveProcesses()` method that you may find interesting.
