### ISSUE TITLE
Paradigm / Comparison Questions about noflo

### ISSUE THREAD

**Issue by ahaw021** [noflo/noflo#629]
I have a few questions that may be more around changing the way I fundamentally break down the problem rather than anything else

I have used NodeRed extensively so trying to figure out similarities/differences. 

A) Request Response: If I want to set up a graph that response to an incoming query (eg an HTTP request) is the current practice to pass the HTTP Object (in javascript) and send the response at the end? 

B) Node Configurations: For example what messages to filter, thresholds, URLs to poll etc. Should these be "injected" via another node at run time? I see a lot of people using something like INPUT.txt -> NODE1

C) Global configurations. Does FPB Protocol have the concepts of global namespace objects? 

Generally, I am very impressed with FBP Protocol and the support for multiple run times but just wondering how some other programming concepts such as config files come in to play.

**Comment by bergie** [comment]
A) For that, [noflo-assembly](https://github.com/noflo/noflo-assembly/wiki/Introduction) provides a quite nice approach. See especially https://github.com/noflo/noflo-assembly/wiki/Concurrency-handling

B) That's what you'd do with "Initial Information Packets", see http://www.jpaulmorrison.com/fbp/reusparm.shtml

C) There is no global state, all state used by components needs to be passed in via messages
