### ISSUE TITLE
using subgraph does not trigger error in embedding callback

### ISSUE THREAD

**Issue by Irvenae** [noflo/noflo#631]
Hello, 

I am a newbie in NoFlo and I am encountering an embedding problem. 
I run a graph by calling

```
export const runWorkflow = noflo.asCallback('RunWorkflow', {
  // Provide the project base directory where NoFlo seeks graphs and components
  baseDir: __dirname + '/./'
});

let input = "fail";
runWorkflow({
  in: input
}, (error, result) => {
  // If component sent to its error port, then we'll have err
  if (error) { 
    throw error; 
  }
});
```

with _RunWorkflow.json_ which is a graph with a subgraph. In this graph I generate an error at the error port. However, the callback is not triggered and the program ends without notifying me. When I remove the subgraph the callback is triggered as should be.

I have tried adding the graphs as components to _package.json_, but this didn't work.
Am I doing something wrong or is this a bug?

I will attach this simple example
[fail_case.zip](https://github.com/noflo/noflo/files/3243657/fail_case.zip)

**Comment by jonnor** [comment]
Were you able to resolve the issue, since you closed it? If so please outline the solution, so that others with same issue can also find the fix.
