### ISSUE TITLE
Add data to target port

### ISSUE THREAD

**Issue by mohandass-pat** [noflo/noflo#633]
I'm trying to dynamically build graph on nodejs. Where I can able to add node, edges using the functions like using the below examples.

`graph.addNode('Read', 'filesystem/ReadFile');
graph.addNode('Parse', 'yaml/ParseYaml');
graph.addNode('Errors', 'core/Merge');
// Connect the nodes together
graph.addEdge('Read', 'out', 'Parse', 'in');`

But I want to map one value to input port. How to acheive that using the above functions. 
Like my expected output graph is 
`        {
            "data": 0,
            "tgt": {
                "process": "canvas/MakeRange_lb9hw",
                "port": "from"
            }
        },`

So, how to map data field to the port using functions?

Kindly help me on this. Thanks in advance

**Comment by jonnor** [comment]
Use addIIP()
IIP=Initial Information Packet, a piece of data sent to the inport on graph startup
