### ISSUE TITLE
Rollup Plugin?

### ISSUE THREAD

**Issue by farhan2106** [noflo/noflo#636]
Hello @bergie 

I just found out about FBP and I think it is awesome :) Luckily NoFlow allow me to code in the most greatest programming language i.e. Javascript :smile: 

I am trying to find a Rollup plugin for bundling browser based components but I only manage to find webpack loader. It would be helpful if anyone can point me to an existing Rollup plugin and if there is none, I would be nice if someone can point to noflo docs so that I can build this plugin.

**Comment by bergie** [comment]
I haven't used Rollup, but would be nice to create a plugin that would handle the component loader stuff for NoFlo.

Seems Rollup plugins are not that complicated: https://github.com/lautis/rollup-plugin-coffee-script/blob/master/index.js
