### ISSUE TITLE
Error: Component interaction/ListenChange not available with base

### ISSUE THREAD

**Issue by Khushboo5214** [noflo/noflo#641]
I wanted to run a NoFlo application. I created a noflo component in json fomat and then tried to run it with the command:
 ./node_modules/.bin/noflo-nodejs --graph graphs/Number_game.json but I got an error. 
Please go through the attachment and someone please help me with that.
![image](https://user-images.githubusercontent.com/65649259/85658628-23026100-b6d1-11ea-8d6e-2382b04e24ae.png)

**Comment by trustmaster** [comment]
@Khushboo5214 @TanyaJiyani could you post contents of your `Number_game.json` so that we can debug it?

**Comment by Khushboo5214** [comment]
> @Khushboo5214 @TanyaJiyani could you post contents of your `Number_game.json` so that we can debug it?


Thankyou so much for replying. Here you go...
[Number_game.zip](https://github.com/noflo/noflo/files/4840675/Number_game.zip)

**Comment by bergie** [comment]
the noflo-interaction component you're using is registered as browser-only, so it can't be loaded inside noflo-nodejs
https://github.com/noflo/noflo-interaction/blob/master/components/ListenChange.coffee
