### ISSUE TITLE
How to embed noflo graphs in Javascript code and How to get the result ?

### ISSUE THREAD

**Issue by Khushboo5214** [noflo/noflo#643]
const wrappedGraph = noflo.asCallback('my-app/Components', {
  baseDir: 'C:\Users\DELL\Desktop\my-app',
});

wrappedGraph({
  in: 'foo',
}, (err, result) => {
  if (err) { throw err; }
  console.log(result.out);
});

I have been trying this method by including it in my JS code but what is the next step to get the noflo graph? Can someone help me with the explaination please?

**Comment by bergie** [comment]
Are you getting some specific error? It is a bit unclear what the problem or question here is.

**Comment by bergie** [comment]
Please refer to: https://noflojs.org/documentation/embedding/

There's also https://github.com/noflo/noflo-wrapper if that feels more convenient
