### ISSUE TITLE
Svelte support in NoFlo

### ISSUE THREAD

**Issue by FractalHQ** [noflo/noflo#722]
Hey guys!  NoFlo is an amazing project!  Really glad to see development is active lately.  

Would anyone have an idea of how to get Svelte in as a runtime?

**Comment by bergie** [comment]
Svelte is just JavaScript, right? I don't think anything special should be needed

**Comment by FractalHQ** [comment]
@bergie It’s a compiler- so it compiles to vanilla JavaScript- but when writing svelte, its more like a superset of HTML and JS with superpowers.

**Comment by bergie** [comment]
Ok, I'm not really familiar with Svelte, but sounds like it would be a good place to start by looking at how we integrate with webpack: https://github.com/noflo/noflo-component-loader

**Comment by FractalHQ** [comment]
Thank you!  Do you know of any rollup implementations?
